
package com.kona.demosmsgw.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicesSoap", targetNamespace = "http://Services.laotel.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicesSoap {


    /**
     * 
     * @param msg
     * @return
     *     returns com.kona.demosmsgw.stub.HeaderResult
     */
    @WebMethod(action = "http://Services.laotel.com/sendSMS")
    @WebResult(name = "sendSMSResult", targetNamespace = "http://Services.laotel.com/")
    @RequestWrapper(localName = "sendSMS", targetNamespace = "http://Services.laotel.com/", className = "com.kona.demosmsgw.stub.SendSMS")
    @ResponseWrapper(localName = "sendSMSResponse", targetNamespace = "http://Services.laotel.com/", className = "com.kona.demosmsgw.stub.SendSMSResponse")
    public HeaderResult sendSMS(
        @WebParam(name = "msg", targetNamespace = "http://Services.laotel.com/")
        SendSmsRequest msg);

}
